spring :
  datasource :
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: 1234
    initialization-mode: always

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

#mybatis
mybatis:
#  type-aliases-package: com.app.Gajago.mapper
  mapper-locations:
    - /mapper/**/*.xml